In [717]:
import random
import numpy as np
import time
import math as m
import matplotlib.pyplot as plt

#Emp bees have to select half population, then perform the operators with probability, then select per fitness but onl bees have to select from the population per fitness then perform operators with probability then select per fitness to scout bees in next part of program

lc = np.loadtxt("dtg42.txt")
print(lc)
print(lc[32][38])
lc1=random.sample(range(42),42)
lc2=random.sample(range(42),42)
print(lc1)

#Colony size=120, number=42, reverse probability=0.9, crossover probability=0.8, CN=400

#3 main operators reverse, fitness, mutate(mutation), with employed bee(emp) function, onlooker bee(onl) function, scout bee(exp) function

#Module for reverse operator

#-------------------------------------------------------------------------------------------------------------------------------

def reverse(list):
    l1=list[:]
    #print(l1)
    
    num=random.sample(range(42),2)
    maxr=num[0]
    minr=num[1]
    
    if maxr<minr:
        t=maxr
        maxr=minr
        minr=t
    
    i=0
    s1=[]
    p=0
    
    for c in range(minr, maxr+1, 1):
        s1.append(l1[c])
        i+=1
    #print(s1)
    #print(m.floor(i/2))
    
    s1=s1[::-1]
    #print(s1)
    p=0
    
    for c in range(minr, maxr+1):
        l1[c]=s1[p]
        p+=1
    return l1

lcc=reverse(lc1)
print(lc1)
print(lcc)

#print(fitness(lc1))
#print(fitness(lcc))
#print(fitness(reverse(reverse((lcc)))))

#a=lc1
#a[3],a[6]=a[6],a[3]
#a[4],a[5]=a[5],a[4]
#print(a)
#print(fitness(a))




    



[[ 0.  8. 39. ... 29.  3.  5.]
 [ 8.  0. 45. ... 33. 11. 12.]
 [39. 45.  0. ... 30. 41. 55.]
 ...
 [29. 33. 30. ...  0. 25. 32.]
 [ 3. 11. 41. ... 25.  0.  6.]
 [ 5. 12. 55. ... 32.  6.  0.]]
62.0
[8, 20, 35, 30, 9, 7, 41, 32, 6, 0, 12, 28, 40, 18, 34, 2, 13, 23, 36, 4, 1, 5, 15, 11, 31, 17, 22, 21, 16, 26, 38, 39, 37, 25, 27, 33, 29, 24, 10, 14, 19, 3]
[8, 20, 35, 30, 9, 7, 41, 32, 6, 0, 12, 28, 40, 18, 34, 2, 13, 23, 36, 4, 1, 5, 15, 11, 31, 17, 22, 21, 16, 26, 38, 39, 37, 25, 27, 33, 29, 24, 10, 14, 19, 3]
[8, 20, 35, 30, 9, 7, 41, 28, 12, 0, 6, 32, 40, 18, 34, 2, 13, 23, 36, 4, 1, 5, 15, 11, 31, 17, 22, 21, 16, 26, 38, 39, 37, 25, 27, 33, 29, 24, 10, 14, 19, 3]


In [718]:
#Module for crossover operator

#-------------------------------------------------------------------------------------------------------------------------------

def crossover(list1, list2):
    temp1=list1[:]
    temp2=list2[:]
    
    out=True
    flag=0
    x=1
    
    while x==1:                              #Check if both list have mutually exclusive values else perform again for that
        if out==False and flag==1:
            break
            
        num=random.sample(range(42),2)
        maxr=num[0]
        minr=num[1]

        if maxr<minr:
            t=maxr
            maxr=minr
            minr=t
            
        t1=maxr-minr
        
        if t1>=4:
            flag=1

        l1=[]
        l2=[]

        c=0

        for i in range(minr, maxr+1):
            l1.append(list1[i])
            l2.append(list2[i])
            c+=1
        
        out = any(check in l1 for check in l2) 
        
        if out==True:
            flag=0
    
    #print(maxr)
    #print(minr)
    #print(l1)
    #print(l2)
    
    for i in range(0, 42): 
        for p in range(len(l2)):       #With c, error
            if list1[i]==l2[p]:
                list1[i]=l1[p]
                
    for i in range(0, 42):
        for p in range(len(l1)):
            if list2[i]==l1[p]:
                list2[i]=l2[p]

    p=0
                
    for i in range(minr, maxr+1):
        #for p in range(len(l2)):
        list1[i]=l2[p]
        p+=1
    
    p=0
            
    for i in range(minr, maxr+1):
        #for p in range(len(l1)):
        list2[i]=l1[p]
        p+=1
        
    #print(list1)
    #print(list2)
    #print(fitness(list1))
    #print(fitness(list2))
    #print(fitness(temp1))
    #print(fitness(temp2))
    
    if fitness(list1)<=fitness(temp1) and fitness(list2)<=fitness(temp2):
         return list1, list2
    elif fitness(list1)>fitness(temp1) and fitness(list2)>fitness(temp2):
         return temp1, temp2
    elif fitness(list1)<=fitness(temp1) and fitness(list2)>fitness(temp2):
         return list1, temp2
    elif fitness(list1)>fitness(temp1) and fitness(list2)<=fitness(temp2):
        return temp1, list2
            
print(lc1)
print(lc2)
crossover(lc1, lc2)
print(lc1)
print(lc2)
    
    

[8, 20, 35, 30, 9, 7, 41, 32, 6, 0, 12, 28, 40, 18, 34, 2, 13, 23, 36, 4, 1, 5, 15, 11, 31, 17, 22, 21, 16, 26, 38, 39, 37, 25, 27, 33, 29, 24, 10, 14, 19, 3]
[29, 28, 19, 36, 8, 40, 10, 3, 20, 14, 6, 17, 41, 11, 31, 30, 35, 12, 23, 0, 24, 15, 18, 21, 39, 4, 16, 34, 5, 26, 37, 13, 25, 1, 22, 32, 33, 27, 9, 7, 2, 38]
[9, 6, 35, 36, 8, 40, 10, 3, 20, 0, 12, 28, 7, 18, 34, 2, 13, 23, 30, 4, 1, 5, 15, 11, 31, 17, 22, 21, 16, 26, 38, 39, 37, 25, 27, 33, 29, 24, 41, 14, 19, 32]
[29, 28, 19, 30, 9, 7, 41, 32, 6, 14, 20, 17, 10, 11, 31, 36, 35, 12, 23, 0, 24, 15, 18, 21, 39, 4, 16, 34, 5, 26, 37, 13, 25, 1, 22, 3, 33, 27, 8, 40, 2, 38]


In [719]:
#Module for mutation operator

#-------------------------------------------------------------------------------------------------------------------------------
def mutate(list):
    l1=list[:]
    print(l1)
    
    num=random.sample(range(42),2)
    maxr=num[0]
    minr=num[1]
    
    if maxr<minr:
        t=maxr
        maxr=minr
        minr=t
        
    print(maxr)
    print(minr)
    t=l1[maxr]
    l1[maxr]=l1[minr]
    l1[minr]=t
    return l1

print(lc1)
lcp=mutate(lc1)
print(lcp)
print(lc1)


[9, 6, 35, 36, 8, 40, 10, 3, 20, 0, 12, 28, 7, 18, 34, 2, 13, 23, 30, 4, 1, 5, 15, 11, 31, 17, 22, 21, 16, 26, 38, 39, 37, 25, 27, 33, 29, 24, 41, 14, 19, 32]
[9, 6, 35, 36, 8, 40, 10, 3, 20, 0, 12, 28, 7, 18, 34, 2, 13, 23, 30, 4, 1, 5, 15, 11, 31, 17, 22, 21, 16, 26, 38, 39, 37, 25, 27, 33, 29, 24, 41, 14, 19, 32]
38
10
[9, 6, 35, 36, 8, 40, 10, 3, 20, 0, 41, 28, 7, 18, 34, 2, 13, 23, 30, 4, 1, 5, 15, 11, 31, 17, 22, 21, 16, 26, 38, 39, 37, 25, 27, 33, 29, 24, 12, 14, 19, 32]
[9, 6, 35, 36, 8, 40, 10, 3, 20, 0, 12, 28, 7, 18, 34, 2, 13, 23, 30, 4, 1, 5, 15, 11, 31, 17, 22, 21, 16, 26, 38, 39, 37, 25, 27, 33, 29, 24, 41, 14, 19, 32]


In [720]:
#Module for fitness operator

#-------------------------------------------------------------------------------------------------------------------------------

def fitness(list):
    #print(list)
    l1=[]
    
    for i in range(len(list)-1):
        l1.append(lc[list[i]][list[i+1]])
    
    arr=np.array(l1)
    #print(l1)
    #print(len(l1))
    #print(arr)
    
    sum=0
    
    for p in arr:
        sum+=p**2
    
    #print(sum)
    #print(np.sum(arr))
    sum=m.sqrt(sum)
    return np.sum(arr)
    
c1=fitness(lc1)
print(c1)
        

2924.0


In [721]:
#Module for probability operator

#-------------------------------------------------------------------------------------------------------------------------------

def probability(p, q):
    x=random.uniform(0, 10)
    n=(p/q)*10
    
    #print(n)
    #print(x)
    
    if x<n:
        return True
    else:
        return False

print(probability(6,8))


True


In [722]:
#Module for emp

#-------------------------------------------------------------------------------------------------------------------------------

main = [[0]*42 for i in range(60)]

#list12[0]=random.sample(range(42), 42)

for i in range(0, 60):
        main[i]=random.sample(range(42),42)

#print(main)

global bestone
bestone=0

def great(ll):
    min=10000
    
    for l in ll:
        if min>fitness(l):
            min=fitness(l)
            bestone=ll.index(l)
    return min

print(great(main))

def emp():
    count=0
    for l in main:
        #print(count)
        count+=1
        #print(great(main))
        x=probability(4.5, 5)
        y=probability(4, 5)
        #print(x)
        #print(y)
        
        if x==True and y==True:
            #print(l)
            temp=reverse(l)
            if fitness(temp)<=fitness(l):
                #print(l)
                #print(fitness(l))
                l=temp
                #print(l)
                #print(fitness(l))
                main[count-1]=l
                #print(main[count-1])
                if main.index(l)<59:
                    l, main[count]=crossover(l, main[count])
            else: 
                if main.index(l)<59:
                    l, main[count]=crossover(l, main[count])                          #Assumption that crossover doesn't change fitness
        
        elif x==True and y==False:
            temp=reverse(l)
            if fitness(temp)<=fitness(l):
                l=temp
        
        elif x==False and y==True:
            
            c=0
            if main.index(l)<59:
                l, main[count]=crossover(l, main[count])
        
        elif x==False and y==False:
            continue

emp()
print(great(main))
#print(count)
print(main)


2547.0
2533.0


[[24, 33, 29, 12, 26, 9, 10, 18, 17, 30, 23, 2, 40, 0, 37, 1, 21, 39, 5, 19, 31, 38, 25, 35, 15, 3, 8, 34, 6, 32, 36, 41, 11, 20, 14, 27, 13, 22, 16, 4, 28, 7], [36, 18, 1, 34, 14, 5, 11, 6, 39, 15, 26, 9, 40, 8, 3, 24, 0, 37, 12, 41, 2, 25, 17, 21, 19, 7, 29, 35, 38, 31, 32, 10, 23, 20, 4, 27, 13, 22, 16, 28, 30, 33], [33, 26, 0, 34, 14, 29, 11, 6, 39, 15, 8, 10, 9, 30, 40, 27, 41, 25, 12, 1, 28, 32, 22, 17, 19, 16, 3, 35, 4, 18, 5, 13, 7, 2, 24, 31, 38, 37, 20, 21, 23, 36], [6, 24, 22, 20, 34, 30, 25, 14, 16, 38, 5, 15, 0, 18, 17, 23, 3, 1, 12, 39, 33, 28, 32, 31, 8, 19, 2, 11, 7, 10, 37, 41, 26, 9, 35, 27, 40, 29, 4, 13, 21, 36], [2, 3, 7, 21, 36, 29, 41, 10, 11, 13, 9, 20, 38, 33, 25, 4, 30, 1, 22, 14, 15, 28, 6, 17, 19, 32, 24, 26, 34, 39, 18, 16, 23, 40, 0, 35, 12, 37, 5, 8, 31, 27], [14, 26, 18, 12, 38, 19, 29, 24, 32, 20, 30, 4, 8, 33, 31, 35, 22, 3, 10, 27, 28, 36, 21, 6, 17, 11, 13, 1, 15, 5, 23, 39, 7, 34, 0, 9, 37, 16, 25, 41, 40, 2], [0, 17, 28, 41, 16, 38, 33, 5, 18, 37, 

In [723]:
#Module for onl

#-------------------------------------------------------------------------------------------------------------------------------

#print(main)

print(great(main))

p1=0

for l in main:
    p1+=1/(fitness(l))

print(p1)
print(main)

def onl():
    count=0
    for l in main:
        count+=1
        #print("llll")
        c=1/(fitness(l)*p1)
        #print(c)
        c1=probability(c, 1)
        
        if c1==False:
            continue
        
        x=probability(4.5, 5)
        y=probability(4, 5)
        
        if x==True and y==True:
            temp=reverse(l)
            if fitness(temp)<fitness(l):
                l=temp
                main[count-1]=l
                if main.index(l)<59:
                    l, main[count]=crossover(l, main[count])
            else: 
                if main.index(l)<59:
                    l, main[count]=crossover(l, main[count])                          #Assumption that crossover doesn't change fitness
        
        elif x==True and y==False:
            temp=reverse(l)
            if fitness(temp)<fitness(l):
                l=temp
        
        elif x==False and y==True:
            
            c=0
            if main.index(l)<59:
                l, main[count]=crossover(l, main[count])
        
        elif x==False and y==False:
            continue
            
onl()
print(great(main))



2533.0
0.02004120568676734
[[24, 33, 29, 12, 26, 9, 10, 18, 17, 30, 23, 2, 40, 0, 37, 1, 21, 39, 5, 19, 31, 38, 25, 35, 15, 3, 8, 34, 6, 32, 36, 41, 11, 20, 14, 27, 13, 22, 16, 4, 28, 7], [36, 18, 1, 34, 14, 5, 11, 6, 39, 15, 26, 9, 40, 8, 3, 24, 0, 37, 12, 41, 2, 25, 17, 21, 19, 7, 29, 35, 38, 31, 32, 10, 23, 20, 4, 27, 13, 22, 16, 28, 30, 33], [33, 26, 0, 34, 14, 29, 11, 6, 39, 15, 8, 10, 9, 30, 40, 27, 41, 25, 12, 1, 28, 32, 22, 17, 19, 16, 3, 35, 4, 18, 5, 13, 7, 2, 24, 31, 38, 37, 20, 21, 23, 36], [6, 24, 22, 20, 34, 30, 25, 14, 16, 38, 5, 15, 0, 18, 17, 23, 3, 1, 12, 39, 33, 28, 32, 31, 8, 19, 2, 11, 7, 10, 37, 41, 26, 9, 35, 27, 40, 29, 4, 13, 21, 36], [2, 3, 7, 21, 36, 29, 41, 10, 11, 13, 9, 20, 38, 33, 25, 4, 30, 1, 22, 14, 15, 28, 6, 17, 19, 32, 24, 26, 34, 39, 18, 16, 23, 40, 0, 35, 12, 37, 5, 8, 31, 27], [14, 26, 18, 12, 38, 19, 29, 24, 32, 20, 30, 4, 8, 33, 31, 35, 22, 3, 10, 27, 28, 36, 21, 6, 17, 11, 13, 1, 15, 5, 23, 39, 7, 34, 0, 9, 37, 16, 25, 41, 40, 2], [0, 17, 28, 

2533.0


In [724]:
#Module for scout

#-------------------------------------------------------------------------------------------------------------------------------

def exp(p):
    temp=mutate(main[p])
    
    if fitness(temp)<=fitness(main[p]):
        main[p]=temp


In [725]:
#Final Module

#-------------------------------------------------------------------------------------------------------------------------------
print(great(main))

cycle=9
min=10000

for i in range(cycle):
    emp()
    
    onl()
            
    if i%75==0:
        exp(bestone)

print(great(main))
        


2533.0
[30, 33, 29, 5, 26, 9, 10, 18, 17, 1, 39, 21, 40, 8, 3, 24, 0, 37, 12, 19, 31, 38, 25, 35, 15, 23, 2, 34, 6, 32, 36, 41, 11, 20, 14, 27, 13, 22, 16, 4, 28, 7]
11
0


KeyboardInterrupt: 